### ISSUE TITLE
Change login link to a message attachment action button

### ISSUE THREAD

**Issue by d-gubert** [RocketChat/Apps.Google.Calendar#8]
Currently, when authenticating with google, a message is sent to the user containing the full url they need to access to authenticate

![image](https://user-images.githubusercontent.com/1810309/61243499-7aa4f800-a71e-11e9-8940-ceaccc506f1a.png)

A better way to achieve this would be transforming the text into a message attachment action button, similar to the one in the `/calendar list` command, that will take the user to google's authentication screen

**Comment by Gautime** [comment]
Login link has been converted to a single authenticate button to start the authentication process for the user's Gmail account. 
![Screenshot from 2019-07-16 20-49-02](https://user-images.githubusercontent.com/22879639/61321605-8204f800-a829-11e9-8fc7-7e42551964ee.png)
